### ISSUE TITLE
large files - how to handle big projection matrices

### ISSUE THREAD

**Issue by timpx** [the-virtual-brain/tvb-data#2]
Github does not allow to push files more than 100 MB. SEEG headmodel is more than 300 MB.

**Comment by maedoc** [comment]
`<snark>` If you had used fewer than 300 sEEG contacts, it wouldn't be a problem `</snark>`.

In my opinion, `tvb-data` should probably be a module which downloads on first use from some server like ladeluke or the cluster, and caches the downloads locally. MNE-Python does this for their demo and testing datasets

@liadomide can we do something like this?

**Comment by liadomide** [comment]
Git has a limitation in file size in itself, and GitHub limits that again.

Having a Ladeluke for tvb-data is a good idea. It will make our repos lighter.
The downsize would be that we do not have versioning any more (ladeluke is only for sharing and not for history on changes).

We should have one of the Friday discussion on tvb-data, because that entire module needs some more refactor (e.g. which data to maintain there, under what naming schema).

**Comment by maedoc** [comment]
There are intermediate solutions, for example [git annex](https://git-annex.branchable.com) which version s the files without checking them into Git.

**Comment by maedoc** [comment]
on JIRA http://req.thevirtualbrain.org/browse/TVB-2007
